### ISSUE TITLE
blinkenlights display is broken

### ISSUE THREAD

**Issue by michaelsbradleyjr** [OfflineIMAP/offlineimap#160]
I upgraded to the latest release candidate recently, and it's working well.

One thing I was hoping was that the `blinkenlights` ui would have been "fixed" since the previous stable release; however, I'm still experiencing the same problems with it as before. The buggy symptoms are as follows:

Either right away or after a minute or so, the output of `blinkenlights` becomes "garbled" and eventually results in a crash of the python process. Also, the garbled output may trigger the print dialog of my OS (which is pretty weird). After I've killed it or it has crashed, I have to issue a `reset` in the terminal to get things back to normal.

The platforms on which I've experienced problems are Mac OS 10.9, 10.10 (and their point releases); python 2.7.6 - 2.7.9 (installed w/ homebrew); and iTerm2 or Terminal.app (with either `TERM=xterm` or `TERM=xterm-256color`).

For now, I can just use `basic` or `ttyui`, as I've been doing over the past year.  Looking at the commit history for `ui/Curses.py`, I'm wondering if the code has simply bitrotted and/or if its maintainer is not testing it on multiple platforms.

**Comment by nicolas33** [comment]
Yes, we don't test all UI in all available platforms. Could you git bisect the issue, please?

**Comment by michaelsbradleyjr** [comment]
I must admit that I have never performed a `git bisect` nor have I setup offlineimap from source manually (I install w/ mac homebrew).

However, I will try to carve out some time to do both and report on the results. Also, I haven't tested `blinkenlights` on a linux system, so I'm not sure if the same bug is encountered across platforms (i.e. with the most recent offlineimap). I'll make sure to test in that respect as well.

**Comment by rkrug** [comment]
I can confirm this in Terminal as well as iTerm2, OS X Yosemite, also homebrew.

**Comment by nicolas33** [comment]
If you could paste a screenshot, please?

**Comment by rkrug** [comment]
Here it is still OK:
![screenshot 2015-03-19 10 46 01](https://cloud.githubusercontent.com/assets/487172/6728070/2cc8ccda-ce27-11e4-86db-14fe3ce3bc5c.png)

Please see top-left corner
![screenshot 2015-03-19 10 48 13](https://cloud.githubusercontent.com/assets/487172/6728067/2cc2c0a6-ce27-11e4-8293-86eab366395d.png)

Third line from bottom
![screenshot 2015-03-19 10 49 15](https://cloud.githubusercontent.com/assets/487172/6728069/2cc448ae-ce27-11e4-87d9-0a370717e7c9.png)

Totally garbled:
![screenshot 2015-03-19 10 56 52](https://cloud.githubusercontent.com/assets/487172/6728068/2cc450e2-ce27-11e4-9526-f1dcd94b5c7f.png)

Hope this helps,

Rainer

**Comment by nicolas33** [comment]
Thanks. It looks like there's more than one glitch.

I don't get what's wrong in the "third line from bottom" screenshot.

I'll put the screenshots into the wiki if you're fine with that because I don't expect to have much time to dig into this any time soon.

**Comment by OI-mailinglist** [comment]
On 2015-03-19 04:42, Nicolas Sebrecht <notifications@github.com> writes:

> Thanks. It looks like there's more than one glitch.
>
> I don't get what's wrong in the "third line from bottom" screenshot.

There is a "37m[[73m m" on the right.

I'm also on OS X and see the same problems (both with iTerm and
Terminal). If it matters I'm using zsh as my shell.

Alan

-- 
OpenPGP Key ID : 040D0A3B4ED2E5C7

**Comment by rkrug** [comment]
Sure - just go ahead.

I am referring to the 
```37[[73 m m```
after the 
```Gmail @```

If you would like to have further screenshots (or a screencast to see how it is changing?), just let me know.

Rainer

**Comment by rkrug** [comment]
Shell: bash

**Comment by green-tea** [comment]
I've had similar behaviour as long as I've been using OfflineIMAP (~3 years). I always assumed that it was related to multiple sync threads occurring at the same time.

I run under Arch Linux. Shell is zsh. Terminal is urxvt (occasionally with the OfflineIMAP process running in tmux).

**Comment by nicolas33** [comment]
Yes, I wonder if it's there since the beginning of blinkenlights.
Honestly, I never gone for a walk in the Blinkenlights code.

Since it looks quite old, don't expect to get it fixed any time soon.

**Comment by michaelcoyote** [comment]
I get this as well in the new version, but I have an old offlineimap install running 4.0.0 and I confirmed that it didn't have this issue. Works fine and looks nice.  Old system is 4.0.0 on OpenBSD using bash as the shell running in GNU screen.
New install w/ bugs is bash shell in Linux terminal and offlineimap 6.5.4.

**Comment by gaudenz** [comment]
I'm also seeing this with the version that recently reached Debian testing. I did a git bisect on this, but the result is not really clear. There are several commits where I'm not sure if the bug is already present or if it's just another error or UI glitch. I used "git bisect skip" on them. The remaining commits are all done by @spaetz . Here is the complete git bisect log for anyone who want's to have a look:
git bisect start
# bad: [72850e3c232ccb671686ac7ea5790bfc89202382] fix Changelog
git bisect bad 72850e3c232ccb671686ac7ea5790bfc89202382
# bad: [ca1ce256ecb1d56f00c7342b121b6079b536ef0f] v6.5.7
git bisect bad ca1ce256ecb1d56f00c7342b121b6079b536ef0f
# bad: [69838b81a5998bbdf473bde372f54b15220a7637] Release 6.4.4
git bisect bad 69838b81a5998bbdf473bde372f54b15220a7637
# good: [3b096952364b572fa117261c2369472b0d41e44d] v6.3.3
git bisect good 3b096952364b572fa117261c2369472b0d41e44d
# good: [a6480d4959d2747680e75b2351dac8f1aca85fe1] Fix string formatting
git bisect good a6480d4959d2747680e75b2351dac8f1aca85fe1
# good: [fd6261a50f039c21895d4fa9780d00bd0db19474] Create new folders on srcrepo if needed
git bisect good fd6261a50f039c21895d4fa9780d00bd0db19474
# skip: [cbec8bb5b20eb8051aaea2b20f81de9158dab975] Rework UI system to make use of the logging module
git bisect skip cbec8bb5b20eb8051aaea2b20f81de9158dab975
# good: [8970a1500b6b85c7f0c3a9e2c112e63261d2d120] UIBase: Fix and cleanup register/unregisterthread
git bisect good 8970a1500b6b85c7f0c3a9e2c112e63261d2d120
# skip: [4eeb88dd8fff60f11321192cf5ca264e8ddcb3e9] Append, don't truncate, log file
git bisect skip 4eeb88dd8fff60f11321192cf5ca264e8ddcb3e9
# skip: [8dbf62cfdba9924e5e82b041e118f6fe059637da] Add a TODO comment
git bisect skip 8dbf62cfdba9924e5e82b041e118f6fe059637da
# bad: [50e78a8d41ea01c1f077438d9c2d6cf7367575b5] Release v6.4.2
git bisect bad 50e78a8d41ea01c1f077438d9c2d6cf7367575b5
# skip: [33b4a16dac98e303322d2a0e56404e865c762d28] Fix mbox.select(foldername) readonly parameter comparison
git bisect skip 33b4a16dac98e303322d2a0e56404e865c762d28
# good: [3885acf87dd4e14ad28ca63c4818114a1dc95e15] Implement server diagnostics
git bisect good 3885acf87dd4e14ad28ca63c4818114a1dc95e15
# skip: [ccfa747ce65583c2352e6546885a9a47ff59e5cb] Use lock with 'with' statement
git bisect skip ccfa747ce65583c2352e6546885a9a47ff59e5cb
# skip: [7c45e05428e6e6a9437c2f3dc6597e19e864b111] Fix getExitStackTrace call
git bisect skip 7c45e05428e6e6a9437c2f3dc6597e19e864b111
# good: [0ba9634205c005fba3915a76b2857dcb836afc9e] Fix string formatting when port is not given.
git bisect good 0ba9634205c005fba3915a76b2857dcb836afc9e
# skip: [d981d66305d3e8342e74cf5a130339aab1eb5396] Add changelog entry for reworked UI backends
git bisect skip d981d66305d3e8342e74cf5a130339aab1eb5396
# bad: [9a654968fc6d73d3bc45b8191e5bae28ce51ac47] Don't append trailing slash to maildir foldernames
git bisect bad 9a654968fc6d73d3bc45b8191e5bae28ce51ac47
# skip: [d54859a9318baf6d6eb000a82793d3beff20f547] Don't setDaemon explicitly, it's done inherently
git bisect skip d54859a9318baf6d6eb000a82793d3beff20f547
# skip: [bfbd37802525279fbfbd540a6e06eafa60b90921] Add FAQ item on "Mailbox already exists" error
git bisect skip bfbd37802525279fbfbd540a6e06eafa60b90921
# good: [76b0d7cf25ac3049529b3afda906b1207bd708db] imapserver: Make noop() more resitent against dropped connections.
git bisect good 76b0d7cf25ac3049529b3afda906b1207bd708db
# skip: [52ca66f055f5f65a5533b5ede616f140d90b4b51] Reduce log verbosity while scanning Maildir
git bisect skip 52ca66f055f5f65a5533b5ede616f140d90b4b51
# bad: [20f2edfcecfbb14e27a1a9445751ccb0c451eb45] Sanity check to notify us when we call IMAPRepository.getsep() too early
git bisect bad 20f2edfcecfbb14e27a1a9445751ccb0c451eb45
# skip: [74d580bc6892f0a22bbbc573c2418b8fbf839933] Exit "infinite" monitorloop when SyncRunner thread exits
git bisect skip 74d580bc6892f0a22bbbc573c2418b8fbf839933
# bad: [a93c80292d0474420654eb9cfa873ce20a6fbdc8] Curses UI: Simplify text buffer handling
git bisect bad a93c80292d0474420654eb9cfa873ce20a6fbdc8
# skip: [656405616d77b75264a23a86e725884bfeb68632] Drop connection if it might be bad on APPEND
git bisect skip 656405616d77b75264a23a86e725884bfeb68632
# bad: [ab184d84e23a2280d6c501159759027180e07683] Reduce parameter list to account.syncfolder call
git bisect bad ab184d84e23a2280d6c501159759027180e07683
# skip: [006f19aba90640d931f475635a8a69694d498e72] Make releaseconnection a NOOP when conn is None
git bisect skip 006f19aba90640d931f475635a8a69694d498e72
# good: [d4a11c62eaeff9726e7989d5fa2c589449957dce] Fix typos in documentary comments in exemplary config file
git bisect good d4a11c62eaeff9726e7989d5fa2c589449957dce
# skip: [54117e702d78e549df82c0233a3a23a248a78349] Bump bundled imaplib2 to 2.29
git bisect skip 54117e702d78e549df82c0233a3a23a248a78349
# bad: [70125d58e67de1fff83a3e59d9498668153a2d55] Curses UI: make resize behave better
git bisect bad 70125d58e67de1fff83a3e59d9498668153a2d55
# skip: [8195d1410f94de4956047f8dc004c0acc68ee386] Prettify Blinkenlights.sleep()
git bisect skip 8195d1410f94de4956047f8dc004c0acc68ee386
# skip: [d992c66156ccd15eac3d9b92a0a49a375e36b40d] Rework the whole unused get/setExitCause machinery
git bisect skip d992c66156ccd15eac3d9b92a0a49a375e36b40d
# skip: [212e50eb4b53055e247feb29d34e8a007610c5cc] Fix sleeping in the Blinkenlights UI
git bisect skip 212e50eb4b53055e247feb29d34e8a007610c5cc
# skip: [f6f8fc852809798823793d9800577321765e3be4] Simplify the keepalive code a bit
git bisect skip f6f8fc852809798823793d9800577321765e3be4
# only skipped commits left to test
# possible first bad commit: [70125d58e67de1fff83a3e59d9498668153a2d55] Curses UI: make resize behave better
# possible first bad commit: [bfbd37802525279fbfbd540a6e06eafa60b90921] Add FAQ item on "Mailbox already exists" error
# possible first bad commit: [212e50eb4b53055e247feb29d34e8a007610c5cc] Fix sleeping in the Blinkenlights UI
# possible first bad commit: [8dbf62cfdba9924e5e82b041e118f6fe059637da] Add a TODO comment
# possible first bad commit: [74d580bc6892f0a22bbbc573c2418b8fbf839933] Exit "infinite" monitorloop when SyncRunner thread exits
# possible first bad commit: [52ca66f055f5f65a5533b5ede616f140d90b4b51] Reduce log verbosity while scanning Maildir
# possible first bad commit: [ccfa747ce65583c2352e6546885a9a47ff59e5cb] Use lock with 'with' statement
# possible first bad commit: [d54859a9318baf6d6eb000a82793d3beff20f547] Don't setDaemon explicitly, it's done inherently
# possible first bad commit: [4eeb88dd8fff60f11321192cf5ca264e8ddcb3e9] Append, don't truncate, log file
# possible first bad commit: [54117e702d78e549df82c0233a3a23a248a78349] Bump bundled imaplib2 to 2.29
# possible first bad commit: [656405616d77b75264a23a86e725884bfeb68632] Drop connection if it might be bad on APPEND
# possible first bad commit: [006f19aba90640d931f475635a8a69694d498e72] Make releaseconnection a NOOP when conn is None
# possible first bad commit: [33b4a16dac98e303322d2a0e56404e865c762d28] Fix mbox.select(foldername) readonly parameter comparison
# possible first bad commit: [d981d66305d3e8342e74cf5a130339aab1eb5396] Add changelog entry for reworked UI backends
# possible first bad commit: [7c45e05428e6e6a9437c2f3dc6597e19e864b111] Fix getExitStackTrace call
# possible first bad commit: [d992c66156ccd15eac3d9b92a0a49a375e36b40d] Rework the whole unused get/setExitCause machinery
# possible first bad commit: [8195d1410f94de4956047f8dc004c0acc68ee386] Prettify Blinkenlights.sleep()
# possible first bad commit: [f6f8fc852809798823793d9800577321765e3be4] Simplify the keepalive code a bit
# possible first bad commit: [cbec8bb5b20eb8051aaea2b20f81de9158dab975] Rework UI system to make use of the logging module

**Comment by iliastsi** [comment]
I created a [patch](https://github.com/iliastsi/offlineimap/commit/d48663b9bf94ef02e381b6800b79574b6b9e2d6c) that hopefully fixes this. Since I do not use Blinkenlights myself, I would like more people to test this, before submitting a PR. Please let me know. Thanks.

**Comment by nicolas33** [comment]
Also talked in #290.

**Comment by nicolas33** [comment]
Fixed by @iliastsi. Thank you!

**Comment by michaelsbradleyjr** [comment]
blinkenlights UI is still terribly broken on macOS. With the latest release, on my system, after a few seconds the terminal is garbled and after a minute or so the process crashes hard.

```shell
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2555

$ python --version
Python 2.7.12
bash-4.4$ offlineimap --version
7.0.9

$ echo iTerm2 3.0.10
iTerm2 3.0.10
```

**Comment by Knusper** [comment]
This has only the MacOS label, but I also experience the same issues with blinkenlights on Linux.  Also in the newest version, where the Chanelog says that Blinkenlights UI is fixed.  Still horribly broken.... However, does not crash on me...

**Comment by CyrilBrulebois** [comment]
I've moved recently from 6.3.4-1 (Debian 8) to 7.0.12+dfsg1-1 (Debian 9 backported to Debian 8), and I'm seeing broken display as well, possibly due to threading issues and/or escape sequences.

Running offlineimap within screen garbles other windows, so I've been running it in a separate terminal.

However, it has just gotten worse:
```
[190530.319308] offlineimap[14291]: segfault at 31064ab50 ip 00007f85c5ca7ecd sp 00007f85c4084300 error 4 in libncursesw.so.5.9[7f85c5c9f000+35000]
```

and this seems to have pulled the plug on all my terminals at once (I'm using xfce4-terminal which uses a common PID for all windows by default).

I'll try to catch this inside gdb, and will probably file a separate bug report to track this, even if the root cause might be the same for both broken display (reported here) and the crash (to be reported).

**Comment by nicolas33** [comment]
There's not much we can do about the segfault. Something is broken in either python or libncursesw. This should be reported to your distrib. Actually, whatever bad code a python user could write she should *never* hit a segfault.

**Comment by iliastsi** [comment]
I finally managed to reproduce this myself. The reason why this worked for me is because I use only one thread, and as @CyrilBrulebois correctly noted this is a threading issue.

I created a [patch](https://github.com/iliastsi/offlineimap/commit/18223bb957ae6ea81e33e857af3ff50877364f2d) that works for me even in multi-threaded setups. Could you please give it a try?

I couldn't reproduce the segfault, but the blinkenlights UI still crashes when the window becomes too small.

**Comment by CyrilBrulebois** [comment]
@nicolas33 ACK for the segfault part.

@iliastsi I had been running one offlineimap instance par account (instead of a single one for both accounts), and I was still seeing issues, which seems to confirm the thread-related issue (I have a few idlefolders), even if the breakage wasn't necessarily coming up immediately. With your patch, it seems syncing both accounts from a single instance works just fine, even when mails are arriving in various idlefolders at the same time. → Looks great, thanks!

**Comment by iliastsi** [comment]
@michaelsbradleyjr, @Knusper, could you please try the above patch?

**Comment by gaudenz** [comment]
I can confirm that the patch by @iliastsi fixes the issue when applied to the Debian package version 7.0.12+dfsg1-1.

**Comment by nicolas33** [comment]
Patch applied. Thank you much @iliastsi !
