### ISSUE TITLE
Full sync after sync with active maxage leads to excessive disc write

### ISSUE THREAD

**Issue by ff2000** [OfflineIMAP/offlineimap#319]
> This v1.0 template stands in `.github/`.

### General informations

- OfflineIMAP version: 6.7.0
- server name or domain: gmail
- CLI options:

```
[Account GmailAlp]
localrepository = GmailAlp-local
remoterepository = GmailAlp-remote
status_backend = sqlite
postsynchook = /home/franz/bin/tagmail.sh

[Repository GmailAlp-local]
type = Maildir
localfolders = ~/mail/GmailAlp
nametrans = lambda folder: {'archive': '[Google Mail]/Alle Nachrichten',
                            }.get(folder, folder)

[Repository GmailAlp-remote]
type = Gmail
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
nametrans = lambda folder: {'[Google Mail]/Alle Nachrichten': 'archive',
                            }.get(folder, folder)
folderfilter = lambda folder: folder in ['INBOX'] # , 'Sent', '[Google Mail]/Gesendet']
idlefolders = ['INBOX']
```

### Log error

Log does not contain related errors

### Steps to reproduce the error

- Run `offlineimap -a GmailAlp -k "Account GmailAlp:maxage=10"`
- Then run `offlineimap -a GmailAlp`
I get continuous writing at ~200kB/s for 30-60 minutes, offlineimap hangs at:
```
Folder INBOX [acc: GmailAlp]:
 Syncing INBOX: Gmail -> Maildir
```
Running strace on the process reveals, that this might be related to the sqlite cache:
```
$ grep RDWR /tmp/offlineimap_strace
30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 6
30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 6
30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 6
30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 6
30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 6
30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644 <unfinished ...>
30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 6
30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 6
30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 6
30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 6
30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 6
30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 6
30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 6
30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 6
30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 6
30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 6
30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 6
30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 6
[...]
```

**Comment by ff2000** [comment]
Aha! This is not only related to runs completely without maxage, but also when I specify a larger value (tried with maxage=40, so not that much larger than 10).
The use-case for me is to make sure I get all my mails. I had issues with managed mailing lists in the past where I received a bulk of (quite) old messages that lay around in the moderation queue. I want to do full syncs (or syncs with a very large maxage) to fetch those messages from time to time.

**Comment by nicolas33** [comment]
I'm pretty sure the reason is that the cache gets reduced according the value of maxage. IOW, the range of mails matching the value of maxage are kept in the cache and removed otherwise.
When increasing maxage or restarting without maxage, the cache is missing data that must be re-written "from sratch". Hence, the unexpected downloads and disk writes.

That's my guess so we would need check the code.

**Comment by nicolas33** [comment]
Is this reproducible with v6.7.0.3?

**Comment by ff2000** [comment]
Is it only possibly fixed in 6.7.0.3 or also in 7.0.5? Because Gentoo directly jumped to 7.0-series without the 6.7.0.3 (which isn't available in portage, I will report that later), which AFAIR fixes an issue that shows when downgrading from 7.x to 6.7.x. I would happily switch to 7.0-series if I get your OK on this issue.

**Comment by nicolas33** [comment]
Yes, try v7.0.5. I've released v6.7.0.3 only to allow easy downgrade from v7.0-series to the v6.7-series in case of strong breakage. However, I think v7.0.5 is more reliable than v6.7.0.3.

**Comment by ff2000** [comment]
I did the update to v7.0.5. After a first full sync (taking nearly 3 hours - no new mails, no re-downloading of mails, just plain caching) I did an immediate sync with maxage followed by another full sync which then again dropped the cache and did a full re-index. So this is not yet fixed.

Sidenote:
What bothers me is that it takes nearly 3 hours to index something less than 80000 mails. Most of the IO is opening the database, inserting a tiny set of data and closing it again (I wouldn't be surprised if it was only one mail per insert). One can optimize this quite a bit by inserting several sets at once, say 100 or even more. Doing a good job there could probably reduce the time it takes to build up the cache from ZERO dramatically, so no other tweaking would be needed to fix this issue.

**Comment by nicolas33** [comment]
> I did the update to v7.0.5. After a first full sync (taking nearly 3 hours - no new mails, no re-downloading of mails, just plain caching) I did an immediate sync with maxage followed by another full sync which then again dropped the cache and did a full re-index. So this is not yet fixed.

I'm not even sure myself that offlineimap drops the cache with maxage. Also, your sidenote does not help and has wrong assumptions. Delaying writes means offlineimap will be less up-to-date on unexpected kills which leads to duplicates and/or unecessary operations on next run.

maxage is not easy in the code. I'm not surprised that playing with maxage shows some limitations. It was not intended to be changed every day or so. Fast syncs are supposed to be done with the `-q` (quick) CLI option.

While I did not notice any issue with my own use cases I'm willing to help. Please, provide detailed logs and how you get them. Compare the results with other runs. Measure spent time. Make it clear at which step you think there are excessive disk writes and the CLI options you use. A full sync of all your emails is not necessary. Profiling might help, too.

**Comment by nicolas33** [comment]
I believe that @muggenhor found the real culprit of this issue. At least, that's what all the "30045 open("/home/franz/.offlineimap/Account-GmailAlp/LocalStatus-sqlite/INBOX-journal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 6" lines from the logs suggest.

Hence, I'm closing this one in favour of #390.

**Comment by nicolas33** [comment]
Let me add that all those writes are not wrong. They are fully necessary to best recover from unexepected halts. Though, we can optionally improve speed (at the price of reliability) as explained in #390.
